- name: Expense project 
  hosts: frontend
  become: yes

  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Enabled and Started nginx service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes







