- name: Expense project 
  hosts: frontend
  become: yes

  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Enabled and Started nginx service 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove default nginx index page
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: Download frontend content
    ansible.builtin.get_url:
      url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Extract the ZIP file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes 

  - name: copy expense content
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Restart service nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
  

  
      







