- name: Expense project 
  hosts: frontend
  become: yes

  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Enable nginx service 
    ansible.builtin.service:
      name: nginx
      enabled: yes

  - name: Started nginx service 
    ansible.builtin.service:
      name: nginx
      state: started







